repositories:
  - name: longhorn
    url: https://charts.longhorn.io
  - name: metallb
    url: https://metallb.github.io/metallb
  - name: jupyterhub
    url: https://jupyterhub.github.io/helm-chart/

releases:
  # Distributed block storage for Kubernetes
  - name: longhorn
    namespace: longhorn-system
    chart: longhorn/longhorn
    version: 1.6.2

  # Load balancer
  - name: metallb
    chart: metallb/metallb
    namespace: metallb-system
    version: 0.14.5

  # JupyterHub Helm Chart
  - name: jupyterhub
    namespace: jupyterhub
    chart: jupyterhub/jupyterhub
    version: 3.3.8
    values:
      - ./values/jupyterhub.values.yaml
  